// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { fileURLToPath } from "node:url";
import { defineConfig } from "prisma/config";

const envPath = fileURLToPath(new URL("./database/.env", import.meta.url));
dotenv.config({ path: envPath });

export default defineConfig({
  schema: "database/prisma/schema.prisma",
  migrations: {
    path: "database/prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
